"""create tabelas iniciais

Revision ID: 97e599448b62
Revises: eb77c40f1dad
Create Date: 2025-07-07 17:12:44.661643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e599448b62'
down_revision: Union[str, Sequence[str], None] = 'eb77c40f1dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('publico_destino', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=True),
    sa.Column('turno', sa.String(length=10), nullable=True),
    sa.Column('curso', sa.String(length=100), nullable=True),
    sa.Column('disciplina', sa.String(length=100), nullable=True),
    sa.Column('sala', sa.String(length=20), nullable=True),
    sa.Column('docente', sa.String(length=100), nullable=True),
    sa.Column('semestre', sa.Integer(), nullable=True),
    sa.Column('horario_inicial', sa.Time(), nullable=True),
    sa.Column('horario_final', sa.Time(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('noticias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('urlqr', sa.String(length=255), nullable=True),
    sa.Column('data_publicacao', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.Column('data_expiracao', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('setor', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('noticias')
    op.drop_table('horarios')
    op.drop_table('avisos')
    # ### end Alembic commands ###
